--- #YAML:1.0
name: Template-Plugin-Class
version: 0.12
license: perl
distribution_type: module
requires:
  Template: 0
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  Template::Plugin::Class:
    file: lib/Template/Plugin/Class.pm
    version: 0.12
  Template::Plugin::Class::Proxy:
    file: lib/Template/Plugin/Class.pm
    version: 0.12
generated_by: Module::Build version 0.21
