---
name: Template-Plugin-Class
version: 0.13
author:
  - Richard Clamp <richardc@unixbeard.net>
abstract: allow calling of class methods on arbitrary classes
license: perl
requires:
  Template: 0
build_requires:
  Test::More: 0
provides:
  Template::Plugin::Class:
    file: lib/Template/Plugin/Class.pm
    version: 0.13
  Template::Plugin::Class::Proxy:
    file: lib/Template/Plugin/Class.pm
    version: 0.13
generated_by: Module::Build version 0.261
